### ISSUE TITLE
Calculate misorientation between two lists of rotation matrices with shape (N,3,3)

### ISSUE THREAD

**Issue by AdrienBerger38** [arthursn/pyebsd#1]
This code is absolutely great and is helping me a lot in my current work.

I am trying to implement a few new functions tailored for my needs. In particular I'd like to compute misorientation angles between deformed and initial state for every pixel (I have transformed the deformed EBSD map into the undeformed framework and therefore I have two arrays with shape (N,3,3) which are the rotation matrices for every pixel before and after deformation). I can do it easily with a "for" loop and the misorientation function but it is very poorly optimized. I believe it is possible to further vectorize the computation with an extra dimension but I'm having a hard time with the maths and the code. Any idea on how to implement such a function? Sorry if this is not the proper way to ask, I'm new to github. Also thank you so much for this python EBSD analysis tool.

Best regards,
Adrien Berger

**Comment by arthursn** [comment]
Hi Adrien, thanks for the feedback. We now have this discussion tab on github. I think that's the proper place to talk about this. I closing this issue and starting a discussion there so it's also more visible to the community.
Arthur
